name: Deployment to Production Environment

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build-images-and-update-cluster:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Setup Google Cloud SDK
        env: GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        run: |
          curl https://sdk.cloud.google.com | bash > /dev/null;
          source $HOME/google-cloud-sdk/path.bash.inc
          gcloud components update kubectl
          echo $GCP_SERVICE_ACCOUNT_KEY >> service-account-key.json
          gcloud auth activate-service-account --key-file service-account-key.json
          cat service-account-key.json | docker login -u _json_key --password-stdin https://gcr.io
          rm service-account-key.json
          gcloud config set project learning-k8s-380513
          gcloud config set compute/zone us-central1-b
          gcloud container clusters get-credentials multi-cluster
      - name: Deploy
        